### ISSUE TITLE
Good day, what driver is used in sp flash tool?

### ISSUE THREAD

**Issue by pepegrillo1998** [dafish7/Sunmi-v2-Firmware-#2]
Good day, what driver is used in sp flash tool?

**Comment by dafish7** [comment]
MediaTek drivers, the folder in the sp flash tool directory "drivers" has a link to the webpage for the driver needed

**Comment by pepegrillo1998** [comment]
hello can i join the discord i have questions i want to flash the twp to install opengapps, thanks
