### ISSUE TITLE
Discord link dead

### ISSUE THREAD

**Issue by CuriousBat** [dafish7/Sunmi-v2-Firmware-#5]
Hey mate, would love to talk to you about how you do this over discord but the link has died :(
I've got ton of those Deliveroo devices we want to repurpose

Thanks
Curious

**Comment by dafish7** [comment]
Thanks for the message, ill fix the discord link right away!

**Comment by dafish7** [comment]
heres the new link:

https://discord.gg/jHpeHhRWez

also if you are getting the emmc error in sp flash tool i just managed to make a workaround for that
